export const CATEGORY_MAPPING = {
	sports: "-5F1wQ50bue4PA2khE3sM",
	lodging: "-Q1NyL2hihfCdselYbnjo",
	temples_and_shrines: "2bdRQFIcZXrYbhxeWeffc",
	attractions: "F72UQSSv5qnV6dGq2o8t-",
	castles: "KcVqSqCqpBoUqNfNlAkE7",
	scenic_spots: "L34snMa-YMz_jT9erQqe2",
	events: "PFEwpbxaA9UrKET8fDnAt",
	food_and_drink: "Uzldz52slOyT_7tD9MSW3",
	technology: "WpkELU1QduAUsJRvAKneB",
	anime: "hbMworHLCdna9k7lGwgWG",
	nature_and_outdoors: "iW3M5z9QsfI5jnVSJjr5j",
	transportation: "l9bkiReXBvPDuJX6TdvDu",
	historical_sites: "mE5Zf1AWhRKDQNHC_NsmV",
	cultural_sites: "n0OLj1cQnnbM3n-2eOzCj",
	hot_springs: "ncFeNw-5M4iGoDD-A8hBH",
	experiences: "phlunt5HJ3fBcZXrezlHN",
	artisans: "tqy6nsKbGDANBHHt7CQaG",
};
